style: github
template: CHANGELOG-full-history.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/terraform-docs/terraform-docs
options:
  commits:
    filters:
      Type:
        - docs
        - enhance
        - feat
        - fix
        - refactor
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - fix
      - enhance
      - refactor
      - docs
    title_maps:
      docs: Documentation
      enhance: Enhancements
      feat: Features
      fix: Bug Fixes
      refactor: Refactoring
  header:
    pattern: "^(\\w*)?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
