name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Verify 'vendor' dependencies
      run: make verify

    - name: Check formatting of go files
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make goimports checkfmt

    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make golangci lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: always()
      with:
        # Currently we're not able to build Codecov report for
        # PRs originates from the fork. There's an issue to track
        # this and it seems it should get resolved shortly, until
        # then we hope for responsiblity in humanity and use plain
        # text of the token, until further to get rotated.
        #
        # https://github.com/codecov/codecov-action/issues/29
        # token: ${{ secrets.CODECOV_TOKEN }}
        token: 7e230f41-8fa3-4d91-8ce8-3d77b7b3f1c3
        file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binary for current OS/ARCH
      run: make build
