name: prerelease

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  prerelease:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries for all OS/ARCH platforms
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make gox build-all

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/terraform-docs-v*
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
