name: validate

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Verify 'vendor' dependencies
      run: make verify

  checkfmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check formatting of go files
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make goimports checkfmt

  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make golangci lint

  staticcheck:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run staticcheck
      run: make staticcheck

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: always()
      with:
        file: ./coverage.out
